overlay = "."
uploaders = [
    "Alexander Kjäll <alexander.kjall@gmail.com>",
    "Holger Levsen <holger@debian.org>"]
collapse_features = true

[packages."lib+@"]
# exactly one crypto backend must be enabled.  Tests that enable both
# nettle and openssl (e.g. --all-features) are implausible:
test_is_broken = true
[packages.lib]
# exactly one crypto backend must be enabled.  Enabling no backends
# (e.g. --no-default-features) is implausible:
test_is_broken = true
[packages."lib+crypto-botan"]
# problems with botan-3
test_is_broken = true
